
---
version: 2
jobs:
  pr_check:
    docker:  
       - image: circleci/node:13.6.0
    steps:
      - checkout # check out source code to working directory
      - run:
          name: Gradle build
          command: |
            echo "Hello World!"
  build:
    docker:
      - image: circleci/node:13.6.0
    steps:
      - checkout # check out source code to working directory
      - run: npm install
      - run: npm test        
          
workflows:
  version: 2
  pr-check-workflow:
    jobs:
    - pr_check 
  build-workflow:
    jobs:
    - build
      