
---
version: 2
jobs:
  pr_check:
    docker:  
       - image: circleci/node:13.6.0
       - image: circleci/mysql:latest
         command: [--default-authentication-plugin=mysql_native_password]
         environment:
           MYSQL_ROOT_PASSWORD: Master@123
           MYSQL_DATABASE: mydb
           MYSQL_USER: dbuser
           MYSQL_PASSWORD: Master@123
    steps:
      - checkout # check out source code to working directory
      - run:
      # Our primary container isn't MYSQL so run a sleep command until it is ready
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          name: npm build
          command: |
            npm install
      - run:
          name: Install MySQL CLI; Import dummy data; run an example query
          command: |
            sudo apt-get install mysql-client
            mysql -h 127.0.0.1 -u dbuser -pMaster@123 --execute="SHOW DATABASES"
  build:    
    docker:
      - image: circleci/node:13.6.0
    steps:
      - checkout # check out source code to working directory
      - run: npm install
      - run: npm test   

  build_deploy:
    filters:
     branches:
      only:
        -master
    docker:
      - image: circleci/node:13.6.0
    steps:
      - checkout # check out source code to working directory
      - run: npm install
      - run: npm test   

workflows:
  version: 2
  pr-check-workflow:
    jobs:
    - pr_check 

  build-workflow:
    jobs:
    - build
        

  
  build-and-deploy:
    jobs:
    - build_deploy:
        filters:
          branches:
            only:
              -master
      