version: 2
jobs:
  build: 
    filters:
      branches:
        only:
          - ${GIT_BRANCH}   
    docker:
      - image: circleci/python:2.7-jessie      

    steps:
      - checkout
      - run: 
          name: "Setup custom environment variables"
          command: |
            echo 'export MY_ENV_VAR="FOO"' >> $BASH_ENV # Redirect MY_ENV_VAR into $BASH_ENV
      # Run a step to print what branch our code base is on.
     
      - run:
          name: Install packages
          command: sudo apt update && sudo apt install wget zip unzip python2.7 python-pip -y 

      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: install--node
          command: |
            sudo apt-get install curl
            curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -
            sudo apt-get install nodejs
            npm -v 
      - run:
          name: Build Artifact
          command: |
            ls -al
            cd webapp1
            pwd
            ls -al
            npm install
            sudo chown -R circleci /usr/lib/node_modules
            sudo npm install -g mocha
            mocha >> mocha.log &
      - run:
          name: Zip Artifact
          command: |
            echo "Hello current build number is ${CIRCLE_BUILD_NUM}"
            aws configure set default.region us-east-1
            pwd
            ls -al
            sudo rm -r webapp/node_modules/
            mkdir -p codedeploy_artifact
            cp infrastructure/aws/codedeploy/*.sh .
            zip -r csye6225-web-app-${CIRCLE_BUILD_NUM}.zip webapp *.sh *.yml
            ls -al
            mv csye6225-web-app-${CIRCLE_BUILD_NUM}.zip codedeploy_artifact/
            ls -al
            pwd
            cd codedeploy_artifact
            ls -al
            pwd
            cd ..
            pwd
            ls -al  
      - run:
          name: Configure AWS Access Key ID
          command: |
            aws configure set aws_access_key_id \
            ${AWS_ACCESS_KEY} \
            --profile default
      - run:
          name: Configure AWS Secret Access Key
          command: |
            aws configure set aws_secret_access_key \
            ${AWS_SECRET_KEY} \
            --profile default
      - run:
          name: Configure AWS region
          command: |
            aws configure set region ${AWS_REGION} \
            --profile default
      # Install aws code deploy              
      - run:
          name: Upload Artifact to S3
          command: |
            aws s3 cp codedeploy_artifact/csye6225-web-app-${CIRCLE_BUILD_NUM}.zip s3://${S3_BUCKET_ADDR}/deployments/csye6225-web-app-${CIRCLE_BUILD_NUM}.zip
      - run:
          name: Make CodeDeploy API call
          command: |
            echo "calling code deploy"
            aws deploy create-deployment --application-name csye6225-webapp --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name csye6225-webapp-deployment --s3-location bucket=${S3_BUCKET_ADDR},bundleType=zip,key=deployments/csye6225-web-app-${CIRCLE_BUILD_NUM}.zip

  pr_check:
    docker:  
       - image: circleci/node:13.6.0
       
    steps:
      - checkout # check out source code to working directory      
      - run:
          name: npm build
          command: |
            npm install      
   

  build_deploy:
    filters:
     branches:
      only:
        -master
    docker:
      - image: circleci/node:13.6.0
    steps:
      - checkout # check out source code to working directory
      - run: npm install
      - run: npm test   



workflows:
  version: 2
  pr-check-workflow:
    jobs:
    - pr_check 

  build-workflow:
    jobs:
    - build
        

  
  